config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :logins, only: [:new, :create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  has_many :pictures
  has_secure_password
  validates :password, presence: true, length: { maximum: 6 }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include LoginsHelper
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログイン失敗'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_login_path
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def new
    @picture = Picture.new
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.image && @picture.image.url
      render :confirm
    else
      flash.now[:empty] = '画像が添付されていません'
      render :new
    end
  end

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
    if @picture.user_id == current_user.id
      render :edit
    else
      redirect_to new_picture_path
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        flash[:notice] = '投稿完了'
        redirect_to picture_path(@picture.id)
      else
        render :new
      end
    end
  end

  def update
    if params[:back]
      @picture = Picture.new
      render :new
    else
      @picture = Picture.find(params[:id])
      @picture.update(picture_params)
      flash[:notice] = '編集完了'
      redirect_to pictures_path
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.user_id == current_user.id
      @picture.destroy
      redirect_to pictures_path, notice: 'destroyed'
    else
      redirect_to new_picture_path
    end
  end

  private
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email ,:password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper

  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Fbclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
      <ul class="right">
        <li class="right-li"><%= link_to "Profile", user_path(current_user.id) %></li>
        <li class="right-li"><%= link_to "Logout", login_path(current_user.id), method: :delete %></li>
      </ul>
      <% else %>
      <ul class="right">
        <li class="right-li"><%= link_to "Sign up", new_user_path %></li>
        <li class="right-li"><%= link_to "Login", new_login_path %></li>
      </ul>
      <% end %>
    </header>
    <div class="main">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <p>株式会社DOUSHIN</p>
      <p>© 2020 Copyright DOUSHIN Corp.</p>
    </footer>
  </body>
</html>

app/views/logins/new.html.erb
<h1>facebook</h1>
<p>Facebookを使うと、友達や同僚、同級生、仲間たちとつながりを深められます。ケータイ、スマートフォンからもアクセスできます。</p>
<%= form_with(scope: :login, url:logins_path, local:true)do |format| %>
  <%= format.label :email %>
  <%= format.text_field :email %>
  <%= format.label :password %>
  <%= format.password_field :password %>
  <%= format.submit "ログイン" %>
<% end %>

app/views/pictures/confirm.html.erb
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <p><%= @picture.content %></p>
  <%= image_tag(@picture.image.url, class:"sized") if @picture.image && @picture.image.url %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.label :image %>
    <%= image_tag(@picture.image.url, class:"sized") if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit %>
    <%= form.submit "戻る", name: "back" %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<h1>Feeds</h1>
<%= link_to 'New Feed', new_picture_path %>
<table class="main_table">
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.content %></td>
        <td><%= picture.user.name %></td>
        <td><%= image_tag picture.image.url %></td>
        <% if picture.user_id == current_user.id %>
          <td><%= link_to 'Show', picture %><br><%= link_to 'Edit', edit_picture_path(picture.id) %><br><%= link_to 'Destroy', picture_path(picture.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
</table>

<br>

app/views/pictures/new.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <div class="field">
    <%= image_tag(@picture.image.url, class:"sized") if @picture.image && @picture.image.url %>
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @picture.content %>
  <strong>User:</strong>
  <%= @picture.user.name %>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url, class:"sized" %>
</p>
<%= link_to 'Edit', edit_picture_path(@picture.id) %>
<%= link_to 'Back', pictures_path %>

app/views/users/new.html.erb
<h1>facebook</h1>
<p>Facebookを使うと、友達や同僚、同級生、仲間たちとつながりを深められます。ケータイ、スマートフォンからもアクセスできます。</p>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count,"error")%>prohibited this<%= @user.name %>from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model:@user, local:true)do |format| %>
  <%= format.label :name %>
  <%= format.text_field :name %>
  <%= format.label :email %>
  <%= format.text_field :email %>
  <%= format.label :password %>
  <%= format.password_field :password %>
  <%= format.label :password_confirmation %>
  <%= format.password_field :password_confirmation %>
  <%= format.submit "新しいアカウントを作成" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス：<%= @user.email %></p>
<% if current_user %>
  <%= link_to "Create Post", new_picture_path %>
<% end %>